Repository illacloud/illa-builder, pull requests merged in 2023-11, with the labels that each got.

#3046 Fix bar progress value label toggle
  apps/builder/src/widgetLibrary/BarProgressWidget/barProgress.tsx
Labels: hacktoberfest

#2920 Update README.md
  README.md
Labels: Stale, hacktoberfest, HACKTOBERFEST-ACCEPTED

#3380 fix: undo/redo not updating execution tree view
  apps/builder/src/redux/currentApp/executionTree/executionListener.ts
Labels: bug

#3302 Create Barcode-Generator.md
  hacktoberfest2023/awesome-illa-apps/Barcode-Generator.md
Labels: ILLA with AI, hacktoberfest, HACKTOBERFEST-ACCEPTED, Awesome AI Agent, AI Agent
